<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.github.teachingai</groupId>
    <artifactId>langchain4j-examples</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>langchain4j-examples</name>
    <description>Example For Langchain4j</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <fastjson2.version>2.0.57</fastjson2.version>
		<java.version>17</java.version>
        <jsonschema.version>4.36.0</jsonschema.version>
        <langchain4j.version>1.7.1</langchain4j.version>
        <testcontainers.version>1.20.1</testcontainers.version>
    </properties>

    <modules>
        <module>langchain4j-anthropic</module>
        <module>langchain4j-azure-openai</module>
        <module>langchain4j-bedrockai</module>
        <module>langchain4j-chatglm</module>
        <module>langchain4j-coze</module>
        <module>langchain4j-dashscope</module>
        <module>langchain4j-huaweiai-gallery</module>
        <module>langchain4j-huaweiai-pangu</module>
        <module>langchain4j-huggingface</module>
        <module>langchain4j-llmsfreeapi</module>
        <module>langchain4j-localai</module>
        <module>langchain4j-minimax</module>
        <module>langchain4j-mistralai</module>
        <module>langchain4j-moonshotai</module>
        <!-- 基于 ollama 的相关整合示例 -->
        <module>langchain4j-ollama</module>
        <module>langchain4j-ollama-local-model</module>
        <module>langchain4j-ollama-prompt</module>
        <module>langchain4j-ollama-function-calling</module>
        <module>langchain4j-ollama-embedding</module>
        <module>langchain4j-ollama-fine-tuning</module>
        <module>langchain4j-ollama-rag-cassandra</module>
        <module>langchain4j-ollama-rag-chroma</module>
        <module>langchain4j-ollama-rag-es</module>
        <module>langchain4j-ollama-rag-milvus</module>
        <module>langchain4j-ollama-rag-mongodb</module>
        <module>langchain4j-ollama-rag-neo4j</module>
        <module>langchain4j-ollama-rag-opensearch</module>
        <module>langchain4j-ollama-rag-pgvector</module>
        <module>langchain4j-ollama-rag-pinecone</module>
        <module>langchain4j-ollama-rag-qdrant</module>
        <module>langchain4j-ollama-rag-redis</module>
        <module>langchain4j-ollama-rag-weaviate</module>
        <module>langchain4j-ollama-voice-chattts</module>
        <module>langchain4j-ollama-voice-edgetts</module>
        <module>langchain4j-ollama-voice-emoti</module>
        <module>langchain4j-ollama-voice-whisper</module>
        <module>langchain4j-ollama-voice-assistant</module>
        <module>langchain4j-ollama-langfuse</module>
        <module>langchain4j-ollama-prometheus</module>
        <module>langchain4j-ollama-agents</module>
        <module>langchain4j-openai</module>
        <module>langchain4j-qianfan</module>
        <module>langchain4j-vertexai</module>
        <module>langchain4j-vertexai-gemini</module>
        <module>langchain4j-workersai</module>
        <module>langchain4j-zhipuai</module>
        <module>langchain4j-project-naming</module>
        <module>langchain4j-project-sql</module>
    </modules>
<!--
	<repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>-->

    <dependencyManagement>
        <dependencies>
            <!-- https://mvnrepository.com/artifact/org.testcontainers/testcontainers-bom -->
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>${testcontainers.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine -->
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>5.10.3</version>
                <scope>test</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java -->
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>4.27.3</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-common-protos -->
            <dependency>
                <groupId>com.google.api.grpc</groupId>
                <artifactId>proto-google-common-protos</artifactId>
                <version>2.40.0</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>33.2.1-jre</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.alibaba.fastjson2/fastjson2 -->
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.github.victools/jsonschema-generator -->
            <dependency>
                <groupId>com.github.victools</groupId>
                <artifactId>jsonschema-generator</artifactId>
                <version>${jsonschema.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.github.victools/jsonschema-module-jackson -->
            <dependency>
                <groupId>com.github.victools</groupId>
                <artifactId>jsonschema-module-jackson</artifactId>
                <version>${jsonschema.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.github.victools/jsonschema-module-swagger-2 -->
            <dependency>
                <groupId>com.github.victools</groupId>
                <artifactId>jsonschema-module-swagger-2</artifactId>
                <version>${jsonschema.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-bom -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>${langchain4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Langchain4j Base -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-core</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-easy-rag</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j Model Providers -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-anthropic</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-azure-open-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bedrock</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-chatglm</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-cohere</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-dashscope</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-hugging-face</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-jlama</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-jina</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-local-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-mistral-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-nomic</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-ollama</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-open-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-ovh-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-qianfan</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-vertex-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-vertex-ai-gemini</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-workers-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-zhipu-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j Embedding Stores -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-azure-ai-search</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-azure-cosmos-mongo-vcore</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-cassandra</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-chroma</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-elasticsearch</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-infinispan</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-milvus</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-mongodb-atlas</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-neo4j</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-opensearch</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-pgvector</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-pinecone</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-qdrant</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-redis</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-vearch</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-vespa</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-weaviate</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-azure-cosmos-nosql</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j Embeddings -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-all-minilm-l6-v2</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-all-minilm-l6-v2-q</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-bge-small-en</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-bge-small-en-q</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-bge-small-en-v15</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-bge-small-en-v15-q</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-bge-small-zh</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-bge-small-zh-q</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-bge-small-zh-v15</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-bge-small-zh-v15-q</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-e5-small-v2</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embeddings-e5-small-v2-q</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- code execution engines -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-code-execution-engine-graalvm-polyglot</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-code-execution-engine-judge0</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j Document Loaders -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-document-loader-amazon-s3</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-document-loader-azure-storage-blob</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-document-loader-github</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-document-loader-selenium</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-document-loader-tencent-cos</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j Document Parsers -->
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-document-parser-apache-pdfbox -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-document-parser-apache-pdfbox</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-document-parser-apache-poi -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-document-parser-apache-poi</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-document-parser-apache-tika -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-document-parser-apache-tika</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j Embedding Store Filter Parsers -->
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-embedding-store-filter-parser-sql -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-embedding-store-filter-parser-sql</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j Web Searchers -->
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-web-search-engine-google-custom -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-web-search-engine-google-custom</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j Experimental -->
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-experimental-sql -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-experimental-sql</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- Langchain4j For Spring Boot -->
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-spring-boot-starter -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-spring-boot-starter</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-anthropic-spring-boot-starter -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-anthropic-spring-boot-starter</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-azure-ai-search-spring-boot-starter -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-azure-ai-search-spring-boot-starter</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-azure-open-ai-spring-boot-starter -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-azure-open-ai-spring-boot-starter</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-ollama-spring-boot-starter -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-ollama-spring-boot-starter</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-open-ai-spring-boot-starter -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-open-ai-spring-boot-starter</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


</project>
