<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.teachingai</groupId>
    <artifactId>langchain4j-examples</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>langchain4j-examples</name>
    <description>Example For Langchain4j</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>17</java.version>
        <revision>1.0.0-SNAPSHOT</revision>
        <!-- Maven Plugin versions -->
        <maven.version>3.6.3</maven.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven-antrun-plugin.version>3.1.0</maven-antrun-plugin.version>
        <maven-assembly-plugin.version>3.7.1</maven-assembly-plugin.version>
        <maven-clean-plugin.version>3.4.0</maven-clean-plugin.version>
        <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
        <maven-dependency-plugin.version>3.8.0</maven-dependency-plugin.version>
        <maven-deploy-plugin.version>3.1.3</maven-deploy-plugin.version>
        <maven-enforcer-plugin.version>3.5.0</maven-enforcer-plugin.version>
        <maven-gpg-plugin.version>3.2.6</maven-gpg-plugin.version>
        <maven-failsafe-plugin.version>3.0.0</maven-failsafe-plugin.version>
        <maven-flatten-plugin.version>1.7.3</maven-flatten-plugin.version>
        <maven-help-plugin.version>3.5.0</maven-help-plugin.version>
        <maven-install-plugin.version>3.1.3</maven-install-plugin.version>
        <maven-invoker-plugin.version>3.8.0</maven-invoker-plugin.version>
        <maven-jar-plugin.version>3.4.2</maven-jar-plugin.version>
        <maven-javadoc-plugin.version>3.8.0</maven-javadoc-plugin.version>
        <maven-nexus-staging-plugin.version>1.7.0</maven-nexus-staging-plugin.version>
        <maven-release-plugin.version>3.1.1</maven-release-plugin.version>
        <maven-resources-plugin.version>3.3.1</maven-resources-plugin.version>
        <maven-shade-plugin.version>3.6.0</maven-shade-plugin.version>
        <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
        <maven-surefire-plugin.version>3.5.0</maven-surefire-plugin.version>
        <maven-war-plugin.version>3.4.0</maven-war-plugin.version>
        <!-- Dependency Component versions -->
        <commons-compress.version>1.27.1</commons-compress.version>
        <commons-lang3.version>3.18.0</commons-lang3.version>
        <protobuf-java.version>4.31.0</protobuf-java.version>
        <springdoc.version>2.7.0</springdoc.version>
        <google-protos.version>2.57.0</google-protos.version>
        <guava.version>33.4.8-jre</guava.version>
        <fastjson2.version>2.0.58</fastjson2.version>
        <javalin.version>6.7.0</javalin.version>
        <jsonschema.version>4.36.0</jsonschema.version>
        <junit-jupiter.version>5.11.0</junit-jupiter.version>
        <knife4j.version>4.5.0</knife4j.version>
        <langchain4j.version>1.8.0</langchain4j.version>
        <log4j2.version>2.25.2</log4j2.version>
        <pdfbox.version>3.0.5</pdfbox.version>
        <perf4j.version>0.9.16</perf4j.version>
        <sa-token.version>1.44.0</sa-token.version>
        <slf4j2.version>2.0.17</slf4j2.version>
        <testcontainers.version>1.20.1</testcontainers.version>
    </properties>

    <modules>
        <module>langchain4j-anthropic</module>
        <module>langchain4j-azure-openai</module>
        <module>langchain4j-bedrockai</module>
        <module>langchain4j-chatglm</module>
        <module>langchain4j-coze</module>
        <module>langchain4j-dashscope</module>
        <module>langchain4j-huaweiai-gallery</module>
        <module>langchain4j-huaweiai-pangu</module>
        <module>langchain4j-huggingface</module>
        <module>langchain4j-llmsfreeapi</module>
        <module>langchain4j-localai</module>
        <module>langchain4j-minimax</module>
        <module>langchain4j-mistralai</module>
        <module>langchain4j-moonshotai</module>
        <!-- 基于 ollama 的相关整合示例 -->
        <module>langchain4j-ollama-generation</module>
        <module>langchain4j-ollama-local-model</module>
        <module>langchain4j-ollama-prompt</module>
        <module>langchain4j-ollama-tools</module>
        <module>langchain4j-ollama-embedding</module>
        <module>langchain4j-ollama-fine-tuning</module>
        <module>langchain4j-ollama-rag-cassandra</module>
        <module>langchain4j-ollama-rag-chroma</module>
        <module>langchain4j-ollama-rag-es</module>
        <module>langchain4j-ollama-rag-milvus</module>
        <module>langchain4j-ollama-rag-mongodb</module>
        <module>langchain4j-ollama-rag-neo4j</module>
        <module>langchain4j-ollama-rag-opensearch</module>
        <module>langchain4j-ollama-rag-pgvector</module>
        <module>langchain4j-ollama-rag-pinecone</module>
        <module>langchain4j-ollama-rag-qdrant</module>
        <module>langchain4j-ollama-rag-redis</module>
        <module>langchain4j-ollama-rag-weaviate</module>
        <module>langchain4j-ollama-voice-chattts</module>
        <module>langchain4j-ollama-voice-edgetts</module>
        <module>langchain4j-ollama-voice-emoti</module>
        <module>langchain4j-ollama-voice-whisper</module>
        <module>langchain4j-ollama-voice-assistant</module>
        <module>langchain4j-ollama-observation-langfuse</module>
        <module>langchain4j-ollama-observation-prometheus</module>
        <module>langchain4j-ollama-agents</module>
        <module>langchain4j-openai</module>
        <module>langchain4j-qianfan</module>
        <module>langchain4j-vertexai</module>
        <module>langchain4j-vertexai-gemini</module>
        <module>langchain4j-workersai</module>
        <module>langchain4j-zhipuai</module>
        <module>langchain4j-project-naming</module>
        <module>langchain4j-project-sql</module>
        <module>langchain4j-common</module>
    </modules>

    <repositories>
        <repository>
            <id>public</id>
            <name>Public Repositories</name>
            <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>public</id>
            <name>Public Repositories</name>
            <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>${commons-compress.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine -->
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${junit-jupiter.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-micrometer -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-micrometer</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-bundle -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-bundle</artifactId>
                <version>${javalin.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>logback-classic</artifactId>
                        <groupId>ch.qos.logback</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-rendering-commonmark -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-rendering-commonmark</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-rendering-freemarker -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-rendering-freemarker</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-rendering-thymeleaf -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-rendering-thymeleaf</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-rendering-mustache -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-rendering-mustache</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-rendering-pebble -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-rendering-pebble</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-rendering-velocity -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-rendering-velocity</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-utils -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-utils</artifactId>
                <version>${javalin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin/javalin-testtools -->
            <dependency>
                <groupId>io.javalin</groupId>
                <artifactId>javalin-testtools</artifactId>
                <version>${javalin.version}</version>
                <scope>test</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin.community.openapi/javalin-openapi-plugin -->
            <dependency>
                <groupId>io.javalin.community.openapi</groupId>
                <artifactId>javalin-openapi-plugin</artifactId>
                <version>6.7.0-2</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin.community.openapi/javalin-swagger-plugin -->
            <dependency>
                <groupId>io.javalin.community.openapi</groupId>
                <artifactId>javalin-swagger-plugin</artifactId>
                <version>6.7.0-2</version>
                <scope>runtime</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.javalin.community.ssl/ssl-plugin -->
            <dependency>
                <groupId>io.javalin.community.ssl</groupId>
                <artifactId>ssl-plugin</artifactId>
                <version>${javalin.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java -->
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf-java.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-common-protos -->
            <dependency>
                <groupId>com.google.api.grpc</groupId>
                <artifactId>proto-google-common-protos</artifactId>
                <version>2.40.0</version>
            </dependency>
            <!-- http://mvnrepository.com/artifact/com.google.guava/guava -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.alibaba.fastjson2/fastjson2 -->
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.github.victools/jsonschema-generator -->
            <dependency>
                <groupId>com.github.victools</groupId>
                <artifactId>jsonschema-generator</artifactId>
                <version>${jsonschema.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.github.victools/jsonschema-module-jackson -->
            <dependency>
                <groupId>com.github.victools</groupId>
                <artifactId>jsonschema-module-jackson</artifactId>
                <version>${jsonschema.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.github.victools/jsonschema-module-swagger-2 -->
            <dependency>
                <groupId>com.github.victools</groupId>
                <artifactId>jsonschema-module-swagger-2</artifactId>
                <version>${jsonschema.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/dev.langchain4j/langchain4j-bom -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>${langchain4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-bom -->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${log4j2.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox -->
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox-tools -->
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox-tools</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox-debugger -->
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox-debugger</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
            <!-- Perf4J 是一个新的开放源码的性能记录，监测和分析库，主要用于企业Java应用程序。 -->
            <dependency>
                <groupId>org.perf4j</groupId>
                <artifactId>perf4j</artifactId>
                <version>${perf4j.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/cn.dev33/sa-token-bom -->
            <dependency>
                <groupId>cn.dev33</groupId>
                <artifactId>sa-token-bom</artifactId>
                <version>${sa-token.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j2.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-simple -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>${slf4j2.version}</version>
                <scope>test</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.testcontainers/testcontainers-bom -->
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>${testcontainers.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-clean-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven-clean-plugin.version}</version>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <maxmem>512M</maxmem>
                    </configuration>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-deploy-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>${maven-deploy-plugin.version}</version>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-enforcer-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>default-cli</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <phase>validate</phase>
                            <configuration>
                                <rules>
                                    <requireMavenVersion>
                                        <message>
                                            <![CDATA[You are running an older version of Maven. This application requires at least Maven ${maven.version}.]]>
                                        </message>
                                        <version>[${maven.version}.0,)</version>
                                    </requireMavenVersion>
                                    <requireJavaVersion>
                                        <message>
                                            <![CDATA[You are running an older version of Java. This application requires at least JDK ${java.version}.]]>
                                        </message>
                                        <version>[${java.version}.0,)</version>
                                    </requireJavaVersion>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.codehaus.mojo/flatten-maven-plugin -->
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>${maven-flatten-plugin.version}</version>
                    <configuration>
                        <flattenMode>resolveCiFriendliesOnly</flattenMode>
                        <updatePomFile>true</updatePomFile>
                    </configuration>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>flatten.clean</id>
                            <phase>clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-gpg-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>${maven-gpg-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>sign-artifacts</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>sign</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-install-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>${maven-install-plugin.version}</version>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-resources-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven-resources-plugin.version}</version>
                    <!-- 解决资源文件的编码问题 -->
                    <configuration>
                        <!-- 字符集编码 -->
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <nonFilteredFileExtensions>
                            <nonFilteredFileExtension>publicKeys.store</nonFilteredFileExtension>
                        </nonFilteredFileExtensions>
                    </configuration>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-release-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>${maven-release-plugin.version}</version>
                    <configuration>
                        <tagNameFormat>v@{project.version}</tagNameFormat>
                        <autoVersionSubmodules>true</autoVersionSubmodules>
                        <useReleaseProfile>false</useReleaseProfile>
                        <releaseProfiles>release</releaseProfiles>
                        <goals>deploy</goals>
                    </configuration>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-shade-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${maven-shade-plugin.version}</version>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-source-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                    <configuration>
                        <!-- 跳过单元测试 -->
                        <skip>true</skip>
                        <skipTests>true</skipTests>
                        <argLine>-Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=256m -Dfile.encoding=UTF-8</argLine>
                        <additionalClasspathElements>
                            <additionalClasspathElement>${basedir}/target/test-classes</additionalClasspathElement>
                        </additionalClasspathElements>
                    </configuration>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven-jar-plugin.version}</version>
                    <configuration>
                        <skipIfEmpty>true</skipIfEmpty>
                        <archive>
                            <manifest>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                                <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                            </manifest>
                        </archive>
                    </configuration>
                </plugin>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-javadoc-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven-javadoc-plugin.version}</version>
                    <configuration>
                        <charset>${project.build.sourceEncoding}</charset>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <docencoding>${project.build.sourceEncoding}</docencoding>
                    </configuration>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.sonatype.plugins</groupId>
                    <artifactId>nexus-staging-maven-plugin</artifactId>
                    <version>${maven-nexus-staging-plugin.version}</version>
                    <extensions>true</extensions>
                    <configuration>
                        <serverId>ossrh</serverId>
                        <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                        <autoReleaseAfterClose>true</autoReleaseAfterClose>
                        <!-- <sslAllowAll>true</sslAllowAll> -->
                        <stagingProgressPauseDurationSeconds>60</stagingProgressPauseDurationSeconds>
                        <stagingProgressTimeoutMinutes>20</stagingProgressTimeoutMinutes>
                        <detectBuildFailures>true</detectBuildFailures>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <!--环境检查插件：代码编译前的环境检查 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
            <!-- 编译插件：编译主代码至主输出目录 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <!-- 资源插件：复制主资源文件至主输出目录 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
            </plugin>
            <!-- 单元测试插件 ：执行测试用例 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <!-- jar包生成插件 ：创建项目jar包 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <!-- 源码插件:发布时自动将源码同时发布 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
            <!-- 模块版本管理插件 ：替换 ${revision} -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
            <!-- 安装插件：将项目输出构件安装到本地仓库 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
            </plugin>
            <!-- 发布插件 ：将项目输出构件部署到远程仓库 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>disable-javadoc-doclint</id>
            <activation>
                <jdk>[1.8,)</jdk>
            </activation>
            <properties>
                <additionalparam>-Xdoclint:none</additionalparam>
            </properties>
        </profile>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <!--环境检查插件：代码编译前的环境检查 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                    </plugin>
                    <!-- 编译插件：编译主代码至主输出目录 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                    </plugin>
                    <!-- 资源插件：复制主资源文件至主输出目录 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                    </plugin>
                    <!-- 单元测试插件 ：执行测试用例 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                    <!-- jar包生成插件 ：创建项目jar包 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                    </plugin>
                    <!-- 源码插件:发布时自动将源码同时发布 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                    </plugin>
                    <!-- javadoc -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                    </plugin>
                    <!-- 安装插件：将项目输出构件安装到本地仓库 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-install-plugin</artifactId>
                    </plugin>
                    <!-- 签名插件：对构建的jar、javadoc、source使用gpg来签名 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                    </plugin>
                    <!-- 发布插件 ：将项目输出构件部署到远程仓库 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-deploy-plugin</artifactId>
                    </plugin>
                    <!-- 版本自动升级插件 ：重置版本号 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-release-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.plugins</groupId>
                        <artifactId>nexus-staging-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
