# Anthropic 配置
langchain4j.anthropic.api-key=
langchain4j.anthropic.chat.options.model=claude-3-5-sonnet-20241022
langchain4j.anthropic.chat.options.temperature=0.7
# Server 配置
server.port=8080
################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging.config=classpath:conf/log4j2-dev.xml
