# Minimax 配置
langchain4j.minimax.api-key=
langchain4j.minimax.group-id=
langchain4j.minimax.chat.options.model=abab5.5-chat
# Server 配置
server.port=8080
################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging.config=classpath:conf/log4j2-dev.xml
