# 智普AI【智普清言】配置
langchain4j.zhipuai.api-key=
langchain4j.zhipuai.chat.enabled=true
langchain4j.zhipuai.chat.options.model=glm-3-turbo
langchain4j.zhipuai.embedding.enabled=true
langchain4j.zhipuai.embedding.options.model=embedding-2
# Server 配置
server.port=8080
################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging.config=classpath:conf/log4j2-dev.xml
