# Server 配置
server.port=8080

# Ollama 配置
langchain4j.ollama.base-url=http://localhost:11434
# Ollama 支持的模型：
langchain4j.ollama.chat.enabled=true
langchain4j.ollama.chat.options.model=qwen:7b
langchain4j.ollama.embedding.enabled=true
langchain4j.ollama.embedding.options.model=mxbai-embed-large

################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging.config=classpath:conf/log4j2-dev.xml
